### ISSUE TITLE
EPIC: Gebeurtenisberichten aanbieden: MVP voor BRP notificaties

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/brp-notificaties#1]
Resultaat: Een omgeving met daarin tot 3 maanden terug alle BRP wijzigingen voor bepaalde gebeurtenissen (verhuizen, overlijden). Omgeving moet op elk moment weer opnieuw van data voorzien kunnen worden (de data in de database zien we als cache, de gebeurtenis berichten bewaren we en moeten opnieuw afspeelbaar zijn).

Qua database: of in een on-premise db (vereist ESB inzet), of in een AWS managed db (Aurora serverless v2 bijvoorbeeld), of in via Athena.
Bij Aurora zo oplossen dat de DB on-demand aan- en uitgaat (zodat die niet 24x 7 aanstaat en geld kost).

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8

**Comment by marnixdessing** [comment]
Wachten op gesprek met afdeling en hoe ze het persoon overleden event nodig hebben.

**Comment by wvdeeckhout** [comment]
Wendy neemt contact op met Jeroen om vervolg te bespreken.
Doel is om een valide berichtenstroom te realiseren, zodat zodra de vraag komt we dit op kunnen pakken.

**Comment by wvdeeckhout** [comment]
Omdat er geen noodzaak meer bij de afdeling is, is dit project gestopt.
